from test_support import *
prove_all(prover=["z3"], counterexample=False)

# some cvc4 issue, possibly related to R308-053
