module Try
  use import int.Int
  use import ref.Ref

  exception Test

(* Valid *)
  let test1 (x : ref int)
    requires { true }
    ensures { !x = old !x + 1 } =
    try raise Test
    with Test -> x := !x + 1
    end

(* Unknown *)
  let test2 (x : ref int)
    requires {true }
    ensures { !x = old !x } =
    try raise Test
    with Test -> x := !x + 1
    end

(* Valid *)
  let test3 (x : ref int)
    requires {true }
    ensures { if old !x > 0 then !x = old !x + 2 else !x = old !x + 1 }
    =
    try
      if !x > 0 then raise Test;
      x := !x + 1
    with Test -> x := !x + 2
    end

(* Unknown *)
  let test4 (x : ref int)
    requires {true }
    ensures { if old !x > 0 then !x = old !x + 1 else !x = old !x + 2 }
    =
    try
      if !x > 0 then raise Test;
      x := !x + 1
    with Test -> x := !x + 2
    end
end

